version: 2.1

setup: true


executors:
  default:
    docker:
      - image: cimg/base:stable


orbs:
  dynamic: bjd2385/dynamic-continuation@3.4.0


commands: {}


jobs:
  generate-release:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install gh CLI
          command: |+
            wget https://github.com/cli/cli/releases/download/v2.9.0/gh_2.9.0_linux_amd64.deb -O gh.deb
            sudo dpkg -i gh.deb
      - run:
          name: Generate release
          command: |
            # Get latest tag.
            git fetch --all --tags
            export LATEST_TAG="$(git tag | sort -V | tail -1)"
            echo "$LATEST_TAG"
            # Generate release from tag.
            echo "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null || true
            gh release create "$LATEST_TAG" --generate-notes


workflows:
  circleci-config-pre-commit-hook:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          modules: |
            src
          filters:
            branches:
              ignore:
                - master

      - generate-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
